name: Github Pages Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'release') || contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.7.1

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run build:pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GHB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: playground/dist
